name: Go CI Pipeline

on:
  workflow_call:

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest  
      - name: Run go linting
        run: |
          cd server
          golangci-lint run ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
          
      - name: Build container
        run: |
          l
          cd server
          cd ..
          docker compose build
      - name: Run tests
        run: |
          docker compose up test
