name: Go CI Pipeline

on:
  workflow_call:

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest  
      - name: Run go linting
        run: golangci-lint run server/src/...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
      - name: Build container image
        run: |
          docker compose build --no-cache
      - name: Run tests
        run: |
          docker compose up tests --exit-code-exit
